### ISSUE TITLE
TiDDIT seems to be more sensitive in the version of index files

### ISSUE THREAD

**Issue by chlu0571** [SciLifeLab/TIDDIT#110]
Hi,

I encountered an issue while using TiDDIT/Manta/smoove in a Nextflow workflow to call variants. During the execution of TiDDIT, I received an error message regarding older versions of BAI files. Interestingly, the other callers worked fine and completed successfully.

To resolve the problem with TiDDIT, I re-indexed and managed to complete the process. I'm curious if TiDDIT has additional requirements for index files.

Thank you,

[
![MicrosoftTeams-image (1)](https://github.com/SciLifeLab/TIDDIT/assets/47763975/9178f649-9b88-4271-94b3-cda4306eeca3)
](url)

**Comment by J35P312** [comment]
Hello!
Happy to hear that you solved this issue! 
TIDDIT uses pysam to read the bam file; the “index file is older…” is a warning from pysam, which is triggered while creating the bam file handle, usually this does not cause any trouble.
TIDDIT does not have any particular requirements regarding the index: TIDDIT creates its own dense csi index (you will find it within the tiddit output directory), as such it does not use the premade bam index.
Looking at the error, I can see that the bam file was not found while generating the csi. I guess this was caused by some random issue reading or accessing the bam file, since TIDDIT worked when you reran it. Tell me if the issue pops up again! 

Best regards
Jesper
