### ISSUE TITLE
Unexpected VCF line

### ISSUE THREAD

**Issue by MKaandemir** [SciLifeLab/TIDDIT#115]
Hello,

I used the tool on a low-depth genome sequence, but it returned a VCF line that lacks read support. Could you also give me a command line options to get high quality variants from the tool. Thanks!
```
8    39696269    SV_112_1    N    <DEL>    50    PASS    SVTYPE=DEL;SVLEN=52;END=39696321;REGIONA=39696238,39696269;REGIONB=39696321,39696384;LFA=0,1;LFB=0,1;LTE=0,0;CTG=CCTTTTTATTATTGAGTTTTAGAATTATTTAAATTCTAAATTATCTAAATGTTGTCTTTTCACTGTCTTGATAATATGTTTTGTGTACAAAAGTTTTTAATTTTGA    GT:CN:COV:DV:RV:LQ:RR:DR1/1:0:0.96875,0.18867924528301888,7.6875:0:0:0.0,0.0:0,0:0,0
```

**Comment by J35P312** [comment]
Hello!
I see that this call is supported from the de novo assembly module only! I recommend turning it off in the low-depth data, you can do so by adding the skip assembly parameter to your command:

--skip_assembly

What is the average coverage of your data? You may want to adjust the minimum number of reads and pairs as well.
Best regards
Jesper

**Comment by MKaandemir** [comment]
I am evaluating a tool using both 10X and 30X datasets. I also obtained identical results from the 30X whole genome sequencing (WGS) data. These datasets are from GIAB HG002. Primarily, I will be utilizing the tool with 30X WGS data.

**Comment by MKaandemir** [comment]
> What is the average coverage of your data? You may want to adjust the minimum number of reads and pairs as well.

Could you help with that?

**Comment by J35P312** [comment]
Hello again!
And sorry for slow reply!
I recomend default settings, for your 10X and 30X data.
For the 30X data, you may want to try -p 6 -r6 , those settings will give you higher precision, but lower sensitivity. 
I use the --skip_assembly when Im not interested in small SV (< 1kb), or if I want to speed up the analysis. Otherwise I recommend running the assembler, or adding another caller to your workflow (like manta, which is really good for the small SV).
Good luck!

**Comment by MKaandemir** [comment]
Thanks for the help! Really appreciated.
