### ISSUE TITLE
Stuck after Constructed GC wig

### ISSUE THREAD

**Issue by asylvz** [SciLifeLab/TIDDIT#68]
Hello,
I'm running TIDDIT sv with this command "**python ./TIDDIT.py --sv -o sim10x.tiddit -p 5 --bam sim_10x.bam --ref human_g1k_v37.fasta**". It works fine, however it is stuck close to end as given below. Any idea?

Thanks

working on seqence GL000212.1
working on seqence GL000222.1
working on seqence GL000200.1
working on seqence GL000193.1
working on seqence GL000194.1
working on seqence GL000225.1
working on seqence GL000192.1
signal extraction time consumption= 1116s
Generating GC wig file
Constructed GC wig in 316.929698944 sec

**Comment by J35P312** [comment]
Hello there!
After producing the GC wig, TIDDIT will start running the cluster analysis of discordant pairs and split reads. 
But first it loads the GC and coverage wig, and creates a sqlite database containing the SV signals.
Did you get any type of error? And for how long did you wait?

Normally, this process should be done in less than 10 minutes; but it could be slower if the data is noisy.
Are you running 10X genomics data? I have experienced that the 10X genomics data is noisy and has a wide and strange insert size distribution; therefore, I usually end up with a very large number of discordant pairs, that needs to be loaded into the database and then clustered. That could be the reason of TIDDIT being slow.
Usually TIDDIT need less than 6GB ram memory, but it might need more if the data is noisy.

I have changed so that tiddit uses percentiles instead of standard deviation in the latest TIDDIT release; updating TIDDIT might help. you could also try setting the insert size treshold to manually, just to see if it helps (maybe 100 000bp or so), using the -i parameter.

Good luck!
//Jesper

**Comment by asylvz** [comment]
Thanks for your quick feedback. It's actually a simulated bam with 10x coverage so it should normally run very fast. And I had no problem using this data with Delly, Tardis and Manta. I don't get any error by the way. It's just stuck there and I'm using the newest commit

**Comment by J35P312** [comment]
Hello again!
No problems, and thanks for your patience!

Thanks, for the information, I think I might know the issue then. Recently, I changed TIDDIT so that it  classifies pair having insert size above the 99.9th percentile as discordant. If the library is very clean, the 99.9th percentile could be equal, to the 99.8, 99.7 ... percentile etc.

Maybe that is the case? A simulated library could be almost perfect. I have just pushed  an update so that the treshold is set to ( 99.9th percentile + 100bp), which would solve that issue.

Could you confirm by checking the "LIBRARY STATISTICS" printed by TIDDIT? it will pop up after  1 minute or so. 

The insert size treshold should look reasonable (i.e more than average insert size + 1*stdev insert size).

Good luck!
//jesper

![LIBRARY_STATISTICS](https://user-images.githubusercontent.com/12830429/66715728-e6067080-edc6-11e9-814f-e9bb9e91480e.png)

**Comment by asylvz** [comment]
Thanks.
The statistics are as follows: 
LIBRARY STATISTICS
        Pair orientation = Forward-reverse
        Read length = 99
        Mean Insert length = 366.693
        Std Insert length = 366.67
----------
library stats time consumption= 223s
auto-config orientation: innie
insert size threshold:1136

However it has been struct here for 4 hours:
working on seqence GL000199.1
working on seqence GL000217.1
working on seqence GL000216.1
working on seqence GL000215.1
working on seqence GL000205.1
working on seqence GL000219.1
working on seqence GL000224.1
working on seqence GL000223.1
working on seqence GL000195.1
working on seqence GL000212.1
working on seqence GL000222.1
working on seqence GL000200.1
working on seqence GL000193.1
working on seqence GL000194.1
working on seqence GL000225.1
working on seqence GL000192.1
signal extraction time consumption= 810s

**Comment by J35P312** [comment]
That's tricky! Both the insert size and threshold looks reasonable; normally, there should not be any problems.

Is there anyway that I could replicate or download your bam file? Maybe you have a pipeline that I could download? Then I can see if I can replicate this error.

Otherwise, I have the following tips:

Make sure that you have atleast 6 Gb ram, and at least 5-10 Gb available disk space. 

you could try to use the singularity image, maybe that could be a solution if there's something funky going on with the dependencies or installation. 

Good luck, and sorry for the inconvenience!
//Jesper

**Comment by asylvz** [comment]
Hi Jesper,
I believe you can replicate the problem with our bam. It's here: http://alkanlab.org/share/tiddit/

Thanks,
Arda

**Comment by J35P312** [comment]
Thanks for uploading the bam file!
I have downloaded the bam file and I run TIDDIT using these settings:

Default:

python TIDDIT/TIDDIT.py --sv --bam simu10x.bam -o simu10x_test

and 5 discordant pairs:

python TIDDIT/TIDDIT.py --sv --bam simu10x.bam -o simu10x_test_5pairs -p 5

Both runs completed in about 30 Min; I upload the vcf files for you so that you can continue your benchmarking.

Before installing TIDDIT, I made a new conda environment containing python 2.7, then I cloned and installed the latest version of TIDDIT (I'm using a Linux mint desktop computer).

What version of python are you using? Maybe that is the issue. Have you tested TIDDIT using any other bam file? On my computer, TIDDIT and the simulated bam file are perfectly happy. 

[Simulated10X_bam.zip](https://github.com/SciLifeLab/TIDDIT/files/3730476/Simulated10X_bam.zip)

![clustering](https://user-images.githubusercontent.com/12830429/66851875-062b6080-ef7c-11e9-8c83-6a301feaba91.png)

Good luck!
//Jesper

**Comment by asylvz** [comment]
Then the problem seems to be in our side. However it's weird that we also use Python 2.7.
I'll try to find the problem and let you now. Thank you for your time.

By the way, we converted all our bams to cram. I think you should consider adding cram support.

Thanks,
Arda

**Comment by J35P312** [comment]
It's a very odd error! I think deleting tiddit and reinstlalling it is the best option, then you are sure that everything is clean and up to date.

Thanks for your feedback! I plan to add Cram support soon, I will also get a big pile of cram files to analyse =P. Once again, good luck, and thanks for your patience!
